version: "3"

services:
  app:
    image: yanishub1/projet:latest
    command: python app.py
    ports:
      - "5000:5000"

  redis:
    image: yanishub1/redis:latest
    ports: ["6379"]

  db:
    image: yanishub1/mysql:latest
    hostname: db
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - mysql:/var/lib/mysql
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      
     
volumes:
  mysql:
